version: "3"
services:
  aki-web:
    image: golang:1.20-alpine
    working_dir: /aki-web
    entrypoint: "go run main.go"
    volumes:
      - .:/aki-web


networks:
  default:
    external:
      name: aki-net