version: "3"
services:
  web:
    image: node:18-alpine
    working_dir: /web
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - 8080:8080
    volumes:
      - ./web:/web
    # source: ./
    # target: /web

networks:
  default:
    external:
      name: aki-net
