version: "3"
services:
  aki-web:
    image: golang:1.20-alpine
    working_dir: /aki-web
    entrypoint: "go run main.go"
    volumes:
      - .:/aki-web
  web:
    image: node:18-alpine
    working_dir: /web
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - 8080:8080
    volumes:
      - ./web:/web
    # source: ./
    # target: /web

networks:
  default:
    external:
      name: aki-net
